services:
  - type: web
    name: sheshield
    env: php
    buildCommand: "./render-build.sh"
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sheshield_db
          property: connectionString
      - key: APP_ENV
        value: production

databases:
  - name: sheshield_db
    databaseName: sheshield
    user: sheshield_user
